server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: bff
  profiles:
    active: local
  jackson: # Jackson JSON 직렬화 설정
    default-property-inclusion: non_null  # null 필드 제외 (REST API 모범 사례)
  
  # Reactive Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
    
    # Reactive MongoDB Configuration
    mongodb:
      host: localhost
      port: 27017
      database: projection
      username: root
      password: password
      authentication-database: admin

# BFF Custom Configuration
bff:
  query:
    redis-ttl-seconds: 3600  # 1시간
    mongodb-timeout-ms: 5000
  command:
    msa-timeout-ms: 10000
  services:
    order-service:
      base-url: http://localhost:8080
    dispatch-service:
      base-url: http://localhost:8081
    delivery-service:
      base-url: http://localhost:8082

# Logging Configuration
logging:
  level:
    root: INFO
    vroong.laas.bff: DEBUG
    org.springframework.data.redis: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

