spring:
  application:
    name: bff

server:
  port: 8085

# Gateway 라우팅 설정 (환경별로 오버라이드 가능)
gateway:
  order:
    route-id: order-commands
    path: /api/orders
    methods:
      - POST
    uri: http://localhost:8080
  
  delivery:
    route-id: delivery-commands
    path: /api/deliveries/**
    methods:
      - POST
      - PUT
      - PATCH
      - DELETE
    uri: http://localhost:8081
  
  dispatch:
    route-id: dispatch-commands
    path: /api/dispatches/**
    methods:
      - POST
      - PUT
      - PATCH
      - DELETE
    uri: http://localhost:8082
  
  read-model:
    route-id: read-model-queries
    path: /api/**
    methods:
      - GET
    uri: http://localhost:8083

