spring:
  application:
    name: bff
  cloud:
    gateway:
      routes:
        # Command 라우팅 - Order 서비스
        - id: order-commands
          uri: http://localhost:8080
          predicates:
            - Path=/api/orders
            - Method=POST
        
        # Command 라우팅 - Delivery 서비스
        - id: delivery-commands
          uri: http://localhost:8081
          predicates:
            - Path=/api/deliveries/**
            - Method=POST,PUT,PATCH,DELETE
        
        # Command 라우팅 - Dispatch 서비스
        - id: dispatch-commands
          uri: http://localhost:8082
          predicates:
            - Path=/api/dispatches/**
            - Method=POST,PUT,PATCH,DELETE
        
        # Query 라우팅 - Read-model 서비스 (모든 GET 요청)
        - id: read-model-queries
          uri: http://localhost:8083
          predicates:
            - Path=/api/**
            - Method=GET

server:
  port: 8085

