name: laas-local

services:
  mysql:
    container_name: laas-mysql
    image: mysql/mysql-server:8.0.27
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
#      - mysql_data:/var/lib/mysql
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_USER: 'laas_user'
      MYSQL_PASSWORD: 'laas_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Seoul'
    platform: linux/arm64
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    container_name: laas-zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    platform: linux/arm64

  kafka:
    container_name: laas-kafka
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-init.sh:/usr/local/bin/kafka-init.sh
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    command: >
      bash -c "
      /etc/confluent/docker/run &
      chmod +x /usr/local/bin/kafka-init.sh &&
      /usr/local/bin/kafka-init.sh &&
      wait
      "
    platform: linux/arm64

  redis:
    container_name: laas-redis
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    platform: linux/arm64
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    container_name: laas-mongodb
    image: mongo:7.0.14
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: projection
    volumes:
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/init.js:ro
    platform: linux/arm64
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

#  redis-cluster:
#    container_name: order-redis-cluster
#    image: bitnami/redis-cluster:7.2.4
#    environment:
#      - 'ALLOW_EMPTY_PASSWORD=yes'
#      - 'REDIS_CLUSTER_REPLICAS=0'
#      - 'REDIS_NODES=127.0.0.1 127.0.0.1 127.0.0.1'
#      - 'REDIS_CLUSTER_CREATOR=yes'
#      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
#      - 'REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1'
#      - 'REDIS_CLUSTER_ANNOUNCE_PORT=7001'
#    ports:
#      - '7001:6379'
#
#  localstack:
#    image: localstack/localstack:3.6
#    environment:
#      - SERVICES=s3,sqs
#      - DOCKER_HOST=unix:///var/run/docker.sock
#      - LOCALSTACK_HOST=localhost
#    container_name: order-localstack
#    ports:
#      - "4566:4566"
#    volumes:
#      - "${PWD}/localstack:/etc/localstack/init/ready.d"
#      - "/var/run/docker.sock:/var/run/docker.sock"

#volumes:
#  mysql_data:
