
server:
  port: 8083
  shutdown: graceful

spring:
  application:
    name: projection
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: projection-server
  
  # Redis Configuration  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 100ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
    
    # MongoDB Configuration
    mongodb:
      host: localhost
      port: 27017
      database: projection
      username: root
      password: password
      authentication-database: admin

# Custom Configuration
projection:
  redis:
    ttl-hours: 24
  topics:
    order: order.event
    delivery: delivery.event
    dispatch: dispatch.event
  fallback:
    enabled: true  # Write Service Fallback 활성화
  features:
    consumer:
      enabled: true  # Event Consumer 활성화
    api:
      enabled: true  # Query API 활성화

# MSA Service URLs (Fallback용)
msa:
  order:
    url: http://localhost:8081
  dispatch:
    url: http://localhost:8082
  delivery:
    url: http://localhost:8083

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: false

# Logging
logging:
  level:
    vroong.laas.projection: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.redis: INFO
    org.springframework.data.mongodb: INFO